### ISSUE TITLE
To-be-done tracker

### ISSUE THREAD

**Issue by leonheldattoradex** [leonheldattoradex/oxidizr#1]
In order:

- [ ] Write proper e2e tests with expects to match aktualizr-info functionality
- [ ] Setup tests in CI
- [ ] Split oxidizr into multiple binaries as aktualizr is
- [ ] Tag the repo when it gets to this "aktualizr-info compatibility" stage, so people can use/maintain that if they wish to do so.
- [ ] Refactor most of the options: this will be a nice breakage from aktualizr. I don't like for example how some of the options in aktualizr-info are named, for example

```
  --tls-creds                Outputs TLS credentials
  --tls-root-ca             Outputs TLS Root CA
  --tls-cert                   Outputs TLS client certificate
  --tls-prv-key             Output TLS client private key
```

could be
```
  --tls-creds                                 Outputs TLS credentials
  --tls-root-ca                              Outputs TLS Root CA
  --tls-client-cert                         Outputs TLS client certificate
  --tls-client-private-key             Output TLS client private key
```

or something similar. Make it more ergonomic and break away from legacy.
- [ ] I'd love to always have structured json as a return if possible. Something like a `--json` switch; `jq` is truly nice to parse stuff with and with ship it with Torizon OS.
- [ ] `--secondary-keys` returns so much stuff... it definitely could be somewhat broken into more options.
